### ISSUE TITLE
Setup missing error

### ISSUE THREAD

**Issue by snayff** [jucacrispim/sphinx_pdj_theme#2]
Build fails on pipelines and was erroring locally with a "setup missing" error. The below change to __init__.py seems to solve it. 

`import os

VERSION = '0.1.4'

def get_html_theme_path():
    """Return list of HTML theme paths."""
    cur_dir = os.path.abspath(os.path.dirname(os.path.dirname(__file__)))
    return cur_dir

def setup(app):
    app.add_html_theme('sphinx_pdj_theme',  os.path.abspath(os.path.dirname(__file__)))`

**Comment by jucacrispim** [comment]
Thank you!

I've updated the init file and uploaded `sphinx_pdj_theme==0.1.5` to PyPI.
