### ISSUE TITLE
Pull requests welcome?

### ISSUE THREAD

**Issue by lachlansimpson** [jucacrispim/sphinx_pdj_theme#3]
I'm using this theme, but I'm finding the highlighting provided with the `.. code-block:: bash` directive hard to read. Bash commands like `cd` are coming out dark blue on a black background, and the highlighting used by `:emphasize-lines:` is sufficiently distracting to make the code very difficult to read. Maybe something like [harlequin](https://github.com/nielsmadan/harlequin)?

**Comment by jucacrispim** [comment]
Hi!

You are right. This blue color is very bad. I should have changed it. Pull requests are very welcome. 

The only thing is that I'm trying to use more or less the same colors that I use in my emacs theme
![Captura de tela de 2020-06-24 17-22-36](https://user-images.githubusercontent.com/181743/85624401-3b766b00-b640-11ea-89ab-368daa60b79f.png), so for function names I would like to have a color like #87CEFA. But for bash commands, like ``cd`` I have no preference.

**Comment by jucacrispim** [comment]
I've just changed some stuff in the highlight. Check if got better for you. :)

**Comment by lachlansimpson** [comment]
Thanks - I've checked it out.

**Comment by lachlansimpson** [comment]
Looks great - updated and published again. Thanks.
