### ISSUE TITLE
Remove the top left search field?

### ISSUE THREAD

**Issue by lachlansimpson** [jucacrispim/sphinx_pdj_theme#4]
I've tried removing `sphinx_pdj_theme/search.html` and `sphinx_pdj_theme/searchbox.html` but further than that seems difficult - is there an easy way to remove?

**Comment by jucacrispim** [comment]
Hi. I just released sphinx-pdj-theme==0.4.0 and now you can remove the search using a theme option in your conf.py

```python
html_theme_options = {
    'search': 'hide'
}
```
