### ISSUE TITLE
Use prefers-color-scheme to allow visitor to decide?

### ISSUE THREAD

**Issue by hugovk** [jucacrispim/sphinx_pdj_theme#5]
Would it be possible to use the `prefers-color-scheme` media query to select either a dark or light theme?

The `prefers-color-scheme` media query allows the theme to detect whether the user has requested a dark or light mode, often via an operating system toggle or time-of-day trigger.

* https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme
* https://web.dev/prefers-color-scheme/
* https://caniuse.com/?search=prefers-color-scheme

This would improve accessibility, readability and consistency, and allow the end user to decide on what is easiest for them to read, and when.

Thanks!

**Comment by jucacrispim** [comment]
Hi!

At the moment I have no time, but I'll take a look at it.

Thanx

**Comment by jucacrispim** [comment]
Hey, sorry for the long delay. I just uploaded ``sphinx-pdj-theme==0.3.0`` to pypi and it now supports ``prefers-color-scheme``

**Comment by hugovk** [comment]
Great, thank you very much!
